# DIND build: https://gitlab.com/joenio/continuous-delivery-template/blob/master/.gitlab-ci.yml
stages:
  - test
  - build

variables:
  CI_REGISTRY_IMAGE: websvcpt/badger:$CI_COMMIT_TAG
  CI_REGISTRY_IMAGE_LATEST: websvcpt/badger:latest

test:quality:
  stage: test
  image: node:10-alpine
  script:
    - npm i
    - npm run eslint
  allow_failure: false

test:code:
  stage: test
  image: node:10-alpine
  script:
    - npm i
    - npm run test
  allow_failure: false

build:image:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - echo Building $CI_REGISTRY_IMAGE
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE_LATEST
    - docker push $CI_REGISTRY_IMAGE_LATEST
    - docker image rm $CI_REGISTRY_IMAGE
    - docker image rm $CI_REGISTRY_IMAGE_LATEST
  only:
    - tags # this job will only run for a tag
