name: Run tests

on: push

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.0'
    
    - name: npm install, build, and test
      run: |
        npm ci
        npm run eslint
        npm run test
